const content=document.querySelector('#libraryContent'),filters=document.querySelector('#filters'),search=document.querySelector('#search'),catalogCount=document.querySelector('#catalogCount'),availableCount=document.querySelector('#availableCount'),onlineStat=document.querySelector('#onlineStat'),modal=document.querySelector('#gameModal');let games=[],activeFilter='Все',query='';const ORDER=['Все','Избранное','Mega Drive','PlayStation','Dreamcast','Demo','На двоих'];const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const multi=g=>(g.tags||[]).includes('multiplayer')||/2|3|4/.test(g.players||'');const systemClass=s=>(s||'retro').toLowerCase().replace(/[^a-z0-9]+/g,'-');
function matches(g){if(query&&!([g.title,g.system,g.description,g.year,...(g.tags||[])].join(' ').toLowerCase().includes(query.toLowerCase())))return false;if(activeFilter==='Избранное')return g.featured&&!g.demo;if(activeFilter==='Demo')return g.demo;if(activeFilter==='На двоих')return multi(g);if(activeFilter!=='Все')return g.system===activeFilter&&!g.demo;return true}
function missingButton(g){if(g.experimental)return `<button class="play-button unavailable-button" data-missing="${g.id}">EXPERIMENTAL</button>`;if(g.biosRequired&&!g.biosInstalled)return `<button class="play-button unavailable-button" data-missing="${g.id}">! НУЖЕН BIOS</button>`;return `<button class="play-button unavailable-button" data-missing="${g.id}">+ ДОБАВИТЬ ROM</button>`}
function card(g){const cover=g.cover?`<img src="${esc(g.cover)}" alt="Обложка ${esc(g.title)}" loading="lazy" onerror="this.remove()">`:'';const action=g.playable?`<a class="play-button" href="game.html?id=${encodeURIComponent(g.id)}">▶ ИГРАТЬ</a>`:missingButton(g);return `<article class="game-card ${g.playable?'ready':'missing'} ${g.demo?'demo-card':''}"><div class="cover-wrap"><div class="cover-fallback system-${systemClass(g.system)}"><span>${esc(g.system)}</span><strong>${esc(g.title)}</strong><em>${esc(g.year||'RETRO')}</em></div><div class="cover-art">${cover}</div><div class="cover-shade"></div><span class="platform-badge">${g.demo?'DEMO':esc(g.system)}</span>${g.experimental?'<span class="experimental-badge">EXPERIMENTAL</span>':''}</div><div class="game-card-body"><h4>${esc(g.title)}</h4><p>${esc(g.year||'')}${g.players?` · ${esc(g.players)}`:''}</p><div class="tags">${(g.tags||[]).filter(t=>t!=='homebrew').slice(0,2).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="card-action">${action}</div></div></article>`}
function shelf(title,list,id=''){if(!list.length)return'';return `<section class="game-shelf" ${id?`id="${id}"`:''}><div class="shelf-heading"><div><p>${id==='demo'?'DEMO / HOMEBREW':'КОЛЛЕКЦИЯ'}</p><h3>${esc(title)}</h3></div>${id==='demo'?'<span>Эти игры запускаются прямо в публичном demo.</span>':''}</div><div class="game-grid">${list.map(card).join('')}</div></section>`}
function render(){const sorted=[...games].sort((a,b)=>(a.sort??9999)-(b.sort??9999));if(activeFilter==='Все'&&!query){content.innerHTML=shelf('Избранное',sorted.filter(g=>g.featured&&!g.demo))+shelf('Mega Drive',sorted.filter(g=>g.system==='Mega Drive'&&!g.demo))+shelf('PlayStation',sorted.filter(g=>g.system==='PlayStation'&&!g.demo))+shelf('Dreamcast',sorted.filter(g=>g.system==='Dreamcast'&&!g.demo))+shelf('Попробовать прямо сейчас',sorted.filter(g=>g.demo),'demo');return}const list=sorted.filter(matches);content.innerHTML=list.length?shelf(activeFilter,list):'<div class="loading-card">Ничего не найдено.</div>'}
function renderFilters(){filters.innerHTML=ORDER.map(x=>`<button class="filter ${x===activeFilter?'active':''}" data-filter="${x}">${x}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;renderFilters();render()})}
function openMissing(g){if(!g)return;document.querySelector('#modalTitle').textContent=g.title;document.querySelector('#modalText').textContent=g.experimental?'Dreamcast подготовлен в каталоге, но Flycast WASM пока отмечен как experimental.':g.biosRequired&&!g.biosInstalled?'Для запуска нужен BIOS и собственный ROM.':'Добавьте собственный ROM по указанному пути — карточка станет доступной на вашей установке.';document.querySelector('#modalRom').textContent=`games/roms/${g.romExpected||g.rom||''}`;const bios=g.biosExpected||[];document.querySelector('#modalBiosBox').hidden=!bios.length;document.querySelector('#modalBios').textContent=bios.map(x=>`games/bios/${x}`).join('\n');modal.hidden=false;document.body.classList.add('modal-open')}
content.addEventListener('click',e=>{const b=e.target.closest('[data-missing]');if(b)openMissing(games.find(g=>g.id===b.dataset.missing))});modal?.addEventListener('click',e=>{if(e.target.closest('[data-close-modal]')){modal.hidden=true;document.body.classList.remove('modal-open')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal&&!modal.hidden){modal.hidden=true;document.body.classList.remove('modal-open')}});search?.addEventListener('input',()=>{query=search.value.trim();render()});
fetch('catalog.json',{cache:'no-store'}).then(r=>r.json()).then(data=>{games=data.games||[];catalogCount.textContent=games.filter(g=>!g.demo).length;availableCount.textContent=games.filter(g=>g.playable).length;onlineStat.textContent='—';renderFilters();render()}).catch(()=>content.innerHTML='<div class="loading-card error">Не удалось загрузить demo-каталог.</div>');
